const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Store = require('../models/Store');
const Product = require('../models/Product');

dotenv.config();

const INITIAL_STORES = [
  {
    id: 'store001',
    name: 'Store 1 - Kootanad',
    code: 'STORE-01',
    location: 'Main Road, Near Bus Stand, Kootanad',
    phone: '+91 98765 43210',
    image: '/images/store-kootanad.png',
    maps: 'https://maps.google.com/?q=Kootanad+Kerala',
    status: 'active',
    description: 'Flagship M Store showroom featuring new sealed iPhones and certified pre-owned devices.',
  },
  {
    id: 'store002',
    name: 'Store 2 - Kecheri',
    code: 'STORE-02',
    location: 'Opposite Calicut Road, Kecheri',
    phone: '+91 98765 43211',
    image: '/images/store-kecheri.png',
    maps: 'https://maps.google.com/?q=Kecheri+Kerala',
    status: 'active',
    description: 'Kecheri branch with extensive range of pre-owned iPhones and original Apple gear.',
  },
  {
    id: 'store003',
    name: 'Store 3 - Mattom',
    code: 'STORE-03',
    location: 'Near Church Junction, Mattom',
    phone: '+91 98765 43212',
    image: '/images/store-mattom.png',
    maps: 'https://maps.google.com/?q=Mattom+Kerala',
    status: 'active',
    description: 'Mattom showroom providing hands-on testing, fast trade-ins, and accessory bundles.',
  },
  {
    id: 'store004',
    name: 'Store 4 - Pattambi',
    code: 'STORE-04',
    location: 'Town Centre, Pattambi',
    phone: '+91 98765 43213',
    image: '/images/store-kootanad.png',
    maps: 'https://maps.google.com/?q=Pattambi+Kerala',
    status: 'active',
    description: 'Pattambi M Store branch offering premium Apple sales and expert device support.',
  },
];

const INITIAL_PRODUCTS = [
  {
    id: 'p16promax_kootanad',
    name: 'iPhone 16 Pro Max',
    category: 'iphone-new',
    subCategory: 'iphone-16',
    price: 134910,
    originalPrice: 149900,
    color: 'Natural Titanium',
    storage: '256GB',
    condition: 'Brand New Sealed',
    batteryHealth: 100,
    storeId: 'store001',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '10% OFF',
    description: 'Brand New Sealed Pack iPhone 16 Pro Max 256GB in Natural Titanium with 1 Year Official Apple Warranty. Available at Kootanad M Store.',
  },
  {
    id: 'p16pro_kecheri',
    name: 'iPhone 16 Pro',
    category: 'iphone-new',
    subCategory: 'iphone-16',
    price: 106165,
    originalPrice: 124900,
    color: 'Desert Titanium',
    storage: '128GB',
    condition: 'Brand New Sealed',
    batteryHealth: 100,
    storeId: 'store002',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '15% OFF',
    description: 'Brand New Sealed Pack iPhone 16 Pro 128GB Desert Titanium. Exclusive stock at Kecheri M Store branch.',
  },
  {
    id: 'p15pro_mattom',
    name: 'iPhone 15 Pro',
    category: 'iphone-new',
    subCategory: 'iphone-15',
    price: 87920,
    originalPrice: 109900,
    color: 'Natural Titanium',
    storage: '128GB',
    condition: 'Brand New Sealed',
    batteryHealth: 100,
    storeId: 'store003',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Brand New Sealed Pack iPhone 15 Pro 128GB Natural Titanium. Instant pickup at Mattom branch.',
  },
  {
    id: 'p16plus_pattambi',
    name: 'iPhone 16 Plus',
    category: 'iphone-new',
    subCategory: 'iphone-16',
    price: 85410,
    originalPrice: 94900,
    color: 'Pink',
    storage: '128GB',
    condition: 'Brand New Sealed',
    batteryHealth: 100,
    storeId: 'store004',
    images: ['https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '10% OFF',
    description: 'Brand New Sealed Pack iPhone 16 Plus 128GB Pink with massive screen and all-day battery life. Exclusive at Pattambi M Store.',
  },
  // Store 1 Accessories
  {
    id: 'p9',
    name: 'AirPods Pro (2nd Gen) USB-C',
    category: 'accessory',
    subCategory: 'AirPods & Audio',
    price: 21520,
    originalPrice: 26900,
    color: 'White',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store001',
    images: ['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Brand new sealed AirPods Pro 2nd Gen with MagSafe Charging Case (USB-C). Active Noise Cancellation & Spatial Audio. Available at Kootanad.',
  },
  {
    id: 'p13',
    name: 'Apple HomePod mini',
    category: 'accessory',
    subCategory: 'AirPods & Audio',
    price: 8720,
    originalPrice: 10900,
    color: 'Space Gray',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store001',
    images: ['https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Delivers unexpectedly big 360-degree sound for a compact speaker. Features Siri smart assistant. In stock at Kootanad M Store.',
  },
  // Store 2 Accessories
  {
    id: 'p10',
    name: 'Apple Watch Series 9 GPS 45mm',
    category: 'accessory',
    subCategory: 'Apple Watch',
    price: 35920,
    originalPrice: 44900,
    color: 'Midnight',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store002',
    images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Apple Watch Series 9 featuring S9 SiP chip, double tap gesture control, Always-On display. In stock at Kecheri.',
  },
  {
    id: 'p14',
    name: 'Apple 20W USB-C Power Adapter',
    category: 'accessory',
    subCategory: 'Chargers & Adapters',
    price: 1520,
    originalPrice: 1900,
    color: 'White',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store002',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Original Apple 20W USB-C Power Adapter for rapid charging your iPhone. Stock at Kecheri branch.',
  },
  // Store 3 Accessories
  {
    id: 'p11',
    name: 'Apple MagSafe Charger 15W',
    category: 'accessory',
    subCategory: 'Chargers & Adapters',
    price: 3920,
    originalPrice: 4900,
    color: 'Silver',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store003',
    images: ['https://images.unsplash.com/photo-1622445268465-840246e5045b?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Official Apple MagSafe Charger makes wireless charging effortless. In stock at Mattom M Store branch.',
  },
  {
    id: 'p15_mattom_acc',
    name: 'AirPods Max Wireless Headphones',
    category: 'accessory',
    subCategory: 'AirPods & Audio',
    price: 47920,
    originalPrice: 59900,
    color: 'Space Gray',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store003',
    images: ['https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Apple-designed dynamic driver provides high-fidelity audio. Active Noise Cancellation with Transparency mode. Available at Mattom M Store.',
  },
  // Store 4 Accessories
  {
    id: 'p12',
    name: 'iPhone 15 Pro Silicone Case with MagSafe',
    category: 'accessory',
    subCategory: 'MagSafe Cases',
    price: 4320,
    originalPrice: 5400,
    color: 'Storm Blue',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store004',
    images: ['https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Designed by Apple to complement iPhone 15 Pro. MagSafe Silicone Case. In stock at Pattambi branch.',
  },
  {
    id: 'p16_pattambi_acc',
    name: 'Apple 20W USB-C Power Adapter',
    category: 'accessory',
    subCategory: 'Chargers & Adapters',
    price: 1520,
    originalPrice: 1900,
    color: 'White',
    storage: 'N/A',
    condition: 'Brand New',
    batteryHealth: 100,
    storeId: 'store004',
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&q=80'],
    available: true,
    isOffer: true,
    offerBadge: '20% OFF',
    description: 'Original Apple 20W USB-C Power Adapter for rapid charging your iPhone. Stock at Pattambi branch.',
  },
];

const seedDB = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/mstore_db';
    console.log(`[Seed Script] Connecting to MongoDB: ${mongoUri}`);
    await mongoose.connect(mongoUri);

    await Store.deleteMany({});
    await Product.deleteMany({});

    await Store.insertMany(INITIAL_STORES);
    await Product.insertMany(INITIAL_PRODUCTS);

    console.log('✅ Successfully seeded database with physical stores and clean offer products!');
    process.exit(0);
  } catch (err) {
    console.error('❌ Error seeding database:', err);
    process.exit(1);
  }
};

seedDB();
